## **DATA CLEANING** ##

In [2]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_excel("C:/Users/LENOVO/Documents/3rd YEAR/SEM 2/FYP 2/draft code/SELANGOR.xlsx")

# Display first 5 rows
display(df.head())

# Check dataset information
display(df.info())

# Check missing values
display(df.isnull().sum())

,Property Type,District,Mukim,Scheme Name/Area,Road Name,"Month, Year of Transaction Date",Tenure,Land/Parcel Area,Unit,Main Floor Area,Unit,Unit Level,Transaction Price
0,1 - 1 1/2 Storey Semi-Detached,Gombak,Bandar Batu Arang,KOTA PUTERI BANDAR BARU BT ARANG,JALAN KOTA PUTERI 5/8A,August 2021,Leasehold,228.00,sq.m,74,sq.m,,"RM370,000.00"
1,NaN,NaN,NaN,NaN,JALAN KOTA PUTERI 5/8B,May 2021,Leasehold,394.00,sq.m,74,sq.m,,"RM405,000.00"
2,NaN,NaN,NaN,NaN,JALAN KOTA PUTERI 5/9A,July 2021,Leasehold,345.00,sq.m,94,sq.m,,"RM380,000.00"
3,NaN,NaN,Bandar Gombak Setia,GOMBAK SETIA,JALAN IBUKOTA KIRI,February 2024,Leasehold,623.00,sq.m,157,sq.m,,"RM750,000.00"
4,NaN,NaN,Bandar Selayang,TAMAN SELAYANG MUTIARA,JALAN MUTIARA 3/8A,October 2023,Leasehold,201.00,sq.m,74,sq.m,,"RM315,000.00"

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110835 entries, 0 to 110834
Data columns (total 13 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Property Type                    11 non-null      object
 1   District                         97 non-null      object
 2   Mukim                            1043 non-null    object
 3   Scheme Name/Area                 8693 non-null    object
 4   Road Name                        39666 non-null   object
 5   Month, Year of Transaction Date  89069 non-null   object
 6   Tenure                           89209 non-null   object
 7   Land/Parcel Area                 99741 non-null   object
 8   Unit                             99741 non-null   object
 9   Main Floor Area                  100766 non-null  object
 10  Unit                             100766 non-null  object
 11  Unit Level                       107158 non-null  object
 12  Transaction Price                110835 non-null  object
dtypes: object(13)
memory usage: 11.0+ MB

None

Property Type                      110824
District                           110738
Mukim                              109792
Scheme Name/Area                   102142
Road Name                           71169
Month, Year of Transaction Date     21766
Tenure                              21626
Land/Parcel Area                    11094
Unit                                11094
Main Floor Area                     10069
Unit                                10069
Unit Level                           3677
Transaction Price                       0
dtype: int64

**Standardize Attributes Name**

In [3]:
df.columns = (
    df.columns.str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("/", "_")
    .str.replace(",", "")
)

display(df.columns)

Index(['property_type', 'district', 'mukim', 'scheme_name_area', 'road_name',
       'month_year_of_transaction_date', 'tenure', 'land_parcel_area', 'unit',
       'main_floor_area', 'unit', 'unit_level', 'transaction_price'],
      dtype='object')

**Fill Null Values**

In [4]:
df = df.ffill()
display(df.isnull().sum())

property_type                     0
district                          0
mukim                             0
scheme_name_area                  0
road_name                         0
month_year_of_transaction_date    0
tenure                            0
land_parcel_area                  0
unit                              0
main_floor_area                   0
unit                              0
unit_level                        0
transaction_price                 0
dtype: int64

**Handle Duplicate**

In [5]:
display(df.shape)
df = df.drop_duplicates()
display(df.shape)

(110835, 13)

(110789, 13)

In [6]:
df["transaction_price"] = (
    df["transaction_price"]
    .astype(str)
    .str.replace("RM", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace(".00", "", regex=False)
    .str.strip()
)

df["transaction_price"] = pd.to_numeric(
    df["transaction_price"],
    errors="coerce"
)

display(df["transaction_price"].head())

0    370000
1    405000
2    380000
3    750000
4    315000
Name: transaction_price, dtype: int64

In [7]:
area_columns = ["land_parcel_area", "main_floor_area"]

for col in area_columns:
    
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.extract(r'(\d+\.?\d*)')[0]
    )

    df[col] = pd.to_numeric(df[col], errors="coerce")

display(df[area_columns].head())

   land_parcel_area  main_floor_area
0             228.0             74.0
1             394.0             74.0
2             345.0             94.0
3             623.0            157.0
4             201.0             74.0

In [8]:
df = df.dropna(subset=["transaction_price"])

**Drop Unimportant Attributes**

In [9]:
df = df.drop(columns=["unit"])
df = df.drop(columns=["mukim"])
df = df.drop(columns=["scheme_name_area"])
df = df.drop(columns=["road_name"])
df = df.drop(columns=["unit_level"])
df = df.drop(columns=["land_parcel_area"])
display(df.head())

,property_type,district,month_year_of_transaction_date,tenure,main_floor_area,transaction_price
0,1 - 1 1/2 Storey Semi-Detached,Gombak,August 2021,Leasehold,74.0,370000
1,1 - 1 1/2 Storey Semi-Detached,Gombak,May 2021,Leasehold,74.0,405000
2,1 - 1 1/2 Storey Semi-Detached,Gombak,July 2021,Leasehold,94.0,380000
3,1 - 1 1/2 Storey Semi-Detached,Gombak,February 2024,Leasehold,157.0,750000
4,1 - 1 1/2 Storey Semi-Detached,Gombak,October 2023,Leasehold,74.0,315000

In [10]:
display(df.info())
display(df.isnull().sum())
display(df.head())

<class 'pandas.core.frame.DataFrame'>
Index: 110789 entries, 0 to 110834
Data columns (total 6 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   property_type                   110789 non-null  object
 1   district                        110789 non-null  object
 2   month_year_of_transaction_date  110789 non-null  object
 3   tenure                          110789 non-null  object
 4   main_floor_area                 70951 non-null   float64
 5   transaction_price               110789 non-null  int64
dtypes: float64(1), int64(1), object(4)
memory usage: 5.9+ MB

None

property_type                         0
district                              0
month_year_of_transaction_date        0
tenure                                0
main_floor_area                   39838
transaction_price                     0
dtype: int64

,property_type,district,month_year_of_transaction_date,tenure,main_floor_area,transaction_price
0,1 - 1 1/2 Storey Semi-Detached,Gombak,August 2021,Leasehold,74.0,370000
1,1 - 1 1/2 Storey Semi-Detached,Gombak,May 2021,Leasehold,74.0,405000
2,1 - 1 1/2 Storey Semi-Detached,Gombak,July 2021,Leasehold,94.0,380000
3,1 - 1 1/2 Storey Semi-Detached,Gombak,February 2024,Leasehold,157.0,750000
4,1 - 1 1/2 Storey Semi-Detached,Gombak,October 2023,Leasehold,74.0,315000

In [11]:
df.to_csv("cleaned_selangor_dataset.csv", index=False)

print("Dataset cleaned successfully!")

PermissionError: [Errno 13] Permission denied: 'cleaned_selangor_dataset.csv'

## **DATA PREPROCESSING** ##

In [12]:
features = [
    "property_type",
    "district",
    "month_year_of_transaction_date",
    "tenure",
    "main_floor_area"
]

X = df[features]

y = df["transaction_price"]

In [13]:
display(X.head(30))
display(y.head(30))

,property_type,district,month_year_of_transaction_date,tenure,main_floor_area
0,1 - 1 1/2 Storey Semi-Detached,Gombak,August 2021,Leasehold,74.0
1,1 - 1 1/2 Storey Semi-Detached,Gombak,May 2021,Leasehold,74.0
2,1 - 1 1/2 Storey Semi-Detached,Gombak,July 2021,Leasehold,94.0
3,1 - 1 1/2 Storey Semi-Detached,Gombak,February 2024,Leasehold,157.0
4,1 - 1 1/2 Storey Semi-Detached,Gombak,October 2023,Leasehold,74.0
5,1 - 1 1/2 Storey Semi-Detached,Gombak,December 2023,Leasehold,74.0
6,1 - 1 1/2 Storey Semi-Detached,Gombak,December 2023,Leasehold,74.0
7,1 - 1 1/2 Storey Semi-Detached,Gombak,June 2024,Leasehold,74.0
8,1 - 1 1/2 Storey Semi-Detached,Gombak,April 2022,Leasehold,93.0
9,1 - 1 1/2 Storey Semi-Detached,Gombak,September 2023,Leasehold,70.0
10,1 - 1 1/2 Storey Semi-Detached,Gombak,September 2024,Leasehold,60.0
11,1 - 1 1/2 Storey Semi-Detached,Gombak,September 2024,Leasehold,87.0
12,1 - 1 1/2 Storey Semi-Detached,Gombak,September 2022,Leasehold,74.0
13,1 - 1 1/2 Storey Semi-Detached,Gombak,September 2023,Leasehold,74.0
14,1 - 1 1/2 Storey Semi-Detached,Gombak,January 2025,Leasehold,74.0
15,1 - 1 1/2 Storey Semi-Detached,Gombak,June 2022,Leasehold,74.0
16,1 - 1 1/2 Storey Semi-Detached,Gombak,August 2024,Leasehold,74.0
17,1 - 1 1/2 Storey Semi-Detached,Gombak,September 2024,Leasehold,74.0
18,1 - 1 1/2 Storey Semi-Detached,Gombak,April 2023,Leasehold,74.0
19,1 - 1 1/2 Storey Semi-Detached,Gombak,September 2024,Leasehold,74.0
20,1 - 1 1/2 Storey Semi-Detached,Gombak,June 2023,Leasehold,74.0
21,1 - 1 1/2 Storey Semi-Detached,Gombak,May 2024,Leasehold,79.0
22,1 - 1 1/2 Storey Semi-Detached,Gombak,December 2023,Leasehold,74.0
23,1 - 1 1/2 Storey Semi-Detached,Gombak,June 2024,Leasehold,74.0
24,1 - 1 1/2 Storey Semi-Detached,Gombak,April 2022,Leasehold,74.0
25,1 - 1 1/2 Storey Semi-Detached,Gombak,January 2024,Leasehold,190.0
26,1 - 1 1/2 Storey Semi-Detached,Gombak,March 2021,Leasehold,74.0
27,1 - 1 1/2 Storey Semi-Detached,Gombak,August 2023,Leasehold,96.0
28,1 - 1 1/2 Storey Semi-Detached,Gombak,November 2022,Leasehold,74.0
29,1 - 1 1/2 Storey Semi-Detached,Gombak,July 2024,Leasehold,74.0

0     370000
1     405000
2     380000
3     750000
4     315000
5     440000
6     570000
7     500000
8     450000
9     465000
10    500000
11    540000
12    360000
13    590000
14    129000
15    460000
16    515000
17    590000
18    550000
19    595000
20    480000
21    530000
22    520000
23    495000
24    315000
25    315000
26    450000
27    530000
28    390000
29    350000
Name: transaction_price, dtype: int64

In [14]:
print(X.isnull().sum())

property_type                         0
district                              0
month_year_of_transaction_date        0
tenure                                0
main_floor_area                   39838
dtype: int64

In [15]:
X = pd.get_dummies(X)
display(X.head(10))

,main_floor_area,property_type_1 - 1 1/2 Storey Semi-Detached,property_type_1 - 1 1/2 Storey Terraced,property_type_2 - 2 1/2 Storey Semi-Detached,property_type_2 - 2 1/2 Storey Terraced,property_type_Cluster House,property_type_Condominium/Apartment,property_type_Detached,property_type_Flat,property_type_Low-Cost Flat,...,month_year_of_transaction_date_October 2023,month_year_of_transaction_date_October 2024,month_year_of_transaction_date_October 2025,month_year_of_transaction_date_September 2021,month_year_of_transaction_date_September 2022,month_year_of_transaction_date_September 2023,month_year_of_transaction_date_September 2024,month_year_of_transaction_date_September 2025,tenure_Freehold,tenure_Leasehold
0,74.0,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,74.0,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,94.0,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,157.0,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,74.0,True,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,True
5,74.0,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
6,74.0,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
7,74.0,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
8,93.0,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
9,70.0,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True

In [16]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="median")

X = pd.DataFrame(
    imputer.fit_transform(X),
    columns=X.columns
)

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.9,
    random_state=42
)

In [18]:
display(X_train.shape)
display(X_test.shape)

(11078, 83)

(99711, 83)

## **LINEAR REGRESSION MODEL** ##

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np

In [20]:
lr_model = LinearRegression()

In [21]:
lr_model.fit(X_train, y_train)

LinearRegression()

In [22]:
y_pred = lr_model.predict(X_test)

In [23]:
mae = mean_absolute_error(y_test, y_pred)

print("MAE:", mae)

MAE: 184789.30780354378

In [24]:
mse = mean_squared_error(y_test, y_pred)

print("MSE:", mse)

MSE: 423300626492.6544

In [25]:
rmse = np.sqrt(mse)

print("RMSE:", rmse)

RMSE: 650615.5750461669

In [26]:
r2 = r2_score(y_test, y_pred)

print("R² Score:", r2)

R² Score: -0.3094454594999225

In [27]:
lr_comparison = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": y_pred
})

display(lr_comparison.head(10))

   Actual Price  Predicted Price
0       2300000     1.715296e+06
1        450000     6.845550e+05
2        359000     3.753697e+05
3        380000     3.100045e+05
4        240000     3.622643e+05
5        285000     3.042930e+05
6        688000     7.527489e+05
7        250000     2.580179e+05
8        540000     4.734500e+05
9         25000     2.417225e+05

## **RANDOM FOREST MODEL** ##

In [28]:
from sklearn.ensemble import RandomForestRegressor

In [29]:
rf_model = RandomForestRegressor(
    n_estimators=100,
    max_depth=5,
    random_state=42
)

In [30]:
rf_model.fit(X_train, y_train)

RandomForestRegressor(max_depth=5, random_state=42)

In [31]:
rf_pred = rf_model.predict(X_test)

In [32]:
rf_mae = mean_absolute_error(y_test, rf_pred)
rf_mse = mean_squared_error(y_test, rf_pred)
rf_rmse = np.sqrt(rf_mse)
rf_r2 = r2_score(y_test, rf_pred)

print("Random Forest MAE:", rf_mae)
print("Random Forest RMSE:", rf_rmse)
print("Random Forest R² Score:", rf_r2)

Random Forest MAE: 171087.58828951386
Random Forest RMSE: 308567.4015745826
Random Forest R² Score: 0.7054638609353245

In [33]:
rf_comparison = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": rf_pred
})

display(rf_comparison.head(10))

   Actual Price  Predicted Price
0       2300000     2.067428e+06
1        450000     5.847787e+05
2        359000     4.078514e+05
3        380000     2.118953e+05
4        240000     4.078514e+05
5        285000     4.078514e+05
6        688000     6.367099e+05
7        250000     4.078514e+05
8        540000     5.182888e+05
9         25000     4.078514e+05

## **GRADIENT BOOSTING MODEL** ##

In [34]:
from sklearn.ensemble import GradientBoostingRegressor

In [35]:
gb_model = GradientBoostingRegressor(
    n_estimators=110,
    learning_rate=0.3,
    max_depth=3,
    random_state=42
)

In [36]:
gb_model.fit(X_train, y_train)

GradientBoostingRegressor(learning_rate=0.3, n_estimators=110, random_state=42)

In [37]:
gb_pred = gb_model.predict(X_test)

In [38]:
gb_mae = mean_absolute_error(y_test, gb_pred)
gb_mse = mean_squared_error(y_test, gb_pred)
gb_rmse = np.sqrt(gb_mse)
gb_r2 = r2_score(y_test, gb_pred)

print("Gradient Boosting MAE:", gb_mae)
print("Gradient Boosting RMSE:", gb_rmse)
print("Gradient Boosting R² Score:", gb_r2)

Gradient Boosting MAE: 158134.24572820796
Gradient Boosting RMSE: 300033.5162241888
Gradient Boosting R² Score: 0.7215302363164879

In [39]:
gb_comparison = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": gb_pred
})

display(gb_comparison.head(10))

   Actual Price  Predicted Price
0       2300000     1.730904e+06
1        450000     6.194841e+05
2        359000     4.177233e+05
3        380000     2.140986e+05
4        240000     3.825209e+05
5        285000     3.554182e+05
6        688000     7.027818e+05
7        250000     3.503034e+05
8        540000     5.605753e+05
9         25000     1.967755e+05

## **XGBOOST MODEL** ##

In [40]:
pip install xgboost

Requirement already satisfied: xgboost in c:\users\lenovo\anaconda3\lib\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\users\lenovo\anaconda3\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\users\lenovo\anaconda3\lib\site-packages (from xgboost) (1.16.3)
Note: you may need to restart the kernel to use updated packages.

In [41]:
from xgboost import XGBRegressor

In [68]:
# xgb_model = XGBRegressor(
#     n_estimators=100,
#     learning_rate=0.1,
#     max_depth=3,
#     random_state=42
# )


xgb_model = XGBRegressor(
    n_estimators=1000,
    learning_rate=0.01,
    max_depth=8,
    min_child_weight=5,
    subsample=0.85,
    colsample_bytree=0.85,
    gamma=0.1,
    reg_alpha=0.05,
    reg_lambda=1.5,
    random_state=42,
    objective="reg:squarederror"
)

In [69]:
xgb_model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.85, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=0.1, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.01, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=8,
             max_leaves=None, min_child_weight=5, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=1000,
             n_jobs=None, num_parallel_tree=None, ...)

In [70]:
xgb_pred = xgb_model.predict(X_test)

In [71]:
xgb_mae = mean_absolute_error(y_test, xgb_pred)

xgb_rmse = np.sqrt(
    mean_squared_error(y_test, xgb_pred)
)

xgb_r2 = r2_score(y_test, xgb_pred)

print("MAE:", xgb_mae)
print("RMSE:", xgb_rmse)
print("R²:", xgb_r2)

MAE: 152965.78125
RMSE: 293351.831465222
R²: 0.7337950468063354

In [55]:
xgb_comparison = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": xgb_pred
})

display(xgb_comparison.head(10))

   Actual Price  Predicted Price
0       2300000     2.236506e+06
1        450000     5.920362e+05
2        359000     4.181942e+05
3        380000     2.381807e+05
4        240000     3.757936e+05
5        285000     3.624084e+05
6        688000     7.246758e+05
7        250000     3.581311e+05
8        540000     5.361583e+05
9         25000     2.197372e+05

In [ ]:
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# model = XGBRegressor(
#     n_estimators=300,
#     learning_rate=0.05,
#     max_depth=6,
#     subsample =0.8,
#     colsample_bytree=0.8,
#     random_state=42
# )

# model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

## **MODELS COMPARISON** ##

In [56]:
comparison = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Random Forest",
        "Gradient Boosting",
        "XGBoost"
    ],
    
    "MAE": [
        mae,
        rf_mae,
        gb_mae,
        xgb_mae
    ],
    
    "RMSE": [
        rmse,
        rf_rmse,
        gb_rmse,
        xgb_rmse
    ],
    
    "R2 Score": [
        r2,
        rf_r2,
        gb_r2,
        xgb_r2
    ]
})

display(comparison)

               Model            MAE           RMSE  R2 Score
0  Linear Regression  141119.312668  237012.357747  0.825151
1      Random Forest  149815.541600  183222.057486  0.895510
2  Gradient Boosting  124166.545622  164121.652250  0.916160
3            XGBoost  102398.335938  131351.311771  0.946298

## **SAVE THE BEST MODEL** ##

In [57]:
import joblib

joblib.dump(xgb_model, "XGBoost_model.pkl")

print("Model saved successfully!")

Model saved successfully!

In [58]:
joblib.dump(X.columns.tolist(), "model_features.pkl")

['model_features.pkl']

## **TEST PREDICTION** ##

In [59]:
def predict_house_price(
    property_type,
    district,
    month_year_of_transaction_date,
    tenure,
    main_floor_area
):
    
    input_data = pd.DataFrame({
        "property_type": [property_type],
        "district": [district],
        "month_year_of_transaction_date": [month_year_of_transaction_date],
        "tenure": [tenure],
        "main_floor_area": [main_floor_area]
    })

    # One-hot encoding
    input_data = pd.get_dummies(input_data)

    # Match training columns
    input_data = input_data.reindex(
        columns=X.columns,
        fill_value=0
    )

    prediction = xgb_model.predict(input_data)

    return prediction[0]

In [60]:
price = predict_house_price(
    property_type="Town House",
    district="Gombak",
    tenure="Leasehold",
    month_year_of_transaction_date="April 2022",
    main_floor_area=97
)

print("Predicted House Price: RM", round(price))

Predicted House Price: RM 380025

In [3]:
import platform
import pandas as pd
import numpy as np
import sklearn
import matplotlib
import xgboost

print("===== SOFTWARE VERSION DETAILS =====")
print(f"Python           : {platform.python_version()}")
print(f"Pandas           : {pd.__version__}")
print(f"NumPy            : {np.__version__}")
print(f"Scikit-learn     : {sklearn.__version__}")
print(f"Matplotlib       : {matplotlib.__version__}")
print(f"XGBoost          : {xgboost.__version__}")

===== SOFTWARE VERSION DETAILS =====
Python           : 3.13.9
Pandas           : 2.3.3
NumPy            : 2.3.5
Scikit-learn     : 1.7.2
Matplotlib       : 3.10.6
XGBoost          : 3.2.0

In [4]:
import notebook
print(notebook.__version__)

7.4.5